apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache
  namespace: amq-streams-cdc
  labels:
    app: data-producer
    app.kubernetes.io/part-of: amq-streams-cdc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: data-producer
  namespace: amq-streams-cdc
  labels:
    app: data-producer
    app.kubernetes.io/part-of: amq-streams-cdc-demo
    app.kubernetes.io/component: data-producer
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ultraJeffOrg/amq-streams-cdc-demo.git
      ref: main
    contextDir: quarkus-data-producer
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: ubi8-openjdk-21:1.18
      env:
        - name: MAVEN_ARGS
          value: "package -DskipTests -Dquarkus.package.jar.type=uber-jar"
      # Use incremental builds to reuse Maven cache
      incremental: true
  # Mount Maven cache PVC for faster builds
  mountTrustedCA: false
  resources:
    limits:
      memory: 2Gi
      cpu: "1"
    requests:
      memory: 1Gi
      cpu: 500m
  output:
    to:
      kind: ImageStreamTag
      name: data-producer:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: data-producer
  namespace: amq-streams-cdc
  labels:
    app: data-producer
    app.kubernetes.io/part-of: amq-streams-cdc-demo

