apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-deployment.yaml
  - postgres-secret.yaml
  - postgres-configmap.yaml
  - postgres-deployment.yaml

