apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator
  - kafka
  - databases
  - kafka-connect
  - data-producer

commonLabels:
  app.kubernetes.io/managed-by: kustomize

